name: merge
on:
  push:
    paths:
      - ".github/workflows/merge.yml"
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: merge
  cancel-in-progress: false

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Find PRs
        id: find-prs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          GH_TOKEN: ${{ github.token }}
          TARGET: ${{ github.repository_owner }}
        with:
          script: |
            const script = require('.github/scripts/find-prs');

            return await script({ core, github })

      - name: Merge PRs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
        with:
          script: |
            const { lgtmPRs, failedPRs } = ${{ steps.find-prs.outputs.result }};

            const script = require('.github/scripts/merge');

            await script({ lgtmPRs, failedPRs }, { core, github, exec })
