name: Merge Renovate PRs
on:
  push:
    paths:
      - ".github/workflows/merge.yml"
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: merge
  cancel-in-progress: false

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Merge PRs
        uses: actions/github-script@v7 # v7
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
        with:
          script: |
            const script = require('.github/scripts/merge-renovate-prs.js');

            await script({ core, github, exec })
