name: Validate renovate.yaml
on:
  pull_request:
    paths:
      - default.json
  push:
    paths:
      - default.json
  schedule:
    - cron: '0 0 * * 6,0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: latest
      - run: npm install -g renovate
      - run: renovate-config-validator default.json
